In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Hasil_Scaraping_Dataset_Li_Baterai.csv')
df.head()

,id_charge,id_discharge,working_ion,average_voltage,max_delta_volume_per,charge_space_group,charge_crystal_system,charge_bandgap_minimum,charge_specific_volume_mode,charge_specific_volume_range,...,discharge_covalent_radius_mean,discharge_covalent_radius_deviation,discharge_column_mean,discharge_column_max,discharge_column_min,discharge_total_valence_mean,discharge_stoich_p2,discharge_stoich_p5,discharge_stoich_p7,discharge_stoich_p10
0,mp-95,mp-7507,Li,0.013164,27.945411,229,Cubic,0.000,55.449151,0.0,...,1.725,0.275,1.5,2.0,1.0,0.75,0.520000,0.088000,0.029632,0.006151
1,mp-95,mp-1187126,Li,-0.249733,16.698268,229,Cubic,0.000,55.449151,0.0,...,1.725,0.275,1.5,2.0,1.0,0.75,0.625000,0.238281,0.133545,0.056314
2,mp-95,mp-972285,Li,-0.340509,18.634069,229,Cubic,0.000,55.449151,0.0,...,1.725,0.275,1.5,2.0,1.0,0.75,0.625000,0.238281,0.133545,0.056314
3,mp-96,mp-1125,Li,1.919919,21.099782,13,Monoclinic,2.748,28.100133,0.0,...,1.225,0.225,8.5,16.0,1.0,1.50,0.555556,0.135802,0.058985,0.017358
4,mp-96,mp-1180520,Li,1.443582,10.690249,13,Monoclinic,2.748,28.100133,0.0,...,1.225,0.225,8.5,16.0,1.0,1.50,0.500000,0.062500,0.015625,0.001953

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52402 entries, 0 to 52401
Data columns (total 47 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   id_charge                            52402 non-null  object
 1   id_discharge                         52402 non-null  object
 2   working_ion                          52402 non-null  object
 3   average_voltage                      52402 non-null  float64
 4   max_delta_volume_per                 52402 non-null  float64
 5   charge_space_group                   52402 non-null  int64
 6   charge_crystal_system                52402 non-null  object
 7   charge_bandgap_minimum               52402 non-null  float64
 8   charge_specific_volume_mode          52402 non-null  float64
 9   charge_specific_volume_range         52402 non-null  float64
 10  charge_specific_volume_deviation     52402 non-null  float64
 11  charge_X_mean                        52402 non-null  float64
 12  charge_X_min                         52402 non-null  float64
 13  charge_X_max                         52402 non-null  float64
 14  charge_X_range                       52402 non-null  float64
 15  charge_X_deviation                   52402 non-null  float64
 16  charge_covalent_radius_mean          52402 non-null  float64
 17  charge_covalent_radius_deviation     52402 non-null  float64
 18  charge_column_mean                   52402 non-null  float64
 19  charge_column_max                    52402 non-null  float64
 20  charge_column_min                    52402 non-null  float64
 21  charge_total_valence_mean            52302 non-null  float64
 22  charge_stoich_p2                     52402 non-null  float64
 23  charge_stoich_p5                     52402 non-null  float64
 24  charge_stoich_p7                     52402 non-null  float64
 25  charge_stoich_p10                    52402 non-null  float64
 26  discharge_space_group                52402 non-null  int64
 27  discharge_crystal_system             52402 non-null  object
 28  discharge_bandgap_minimum            52402 non-null  float64
 29  discharge_specific_volume_mode       52402 non-null  float64
 30  discharge_specific_volume_range      52402 non-null  float64
 31  discharge_specific_volume_deviation  52402 non-null  float64
 32  discharge_X_mean                     52402 non-null  float64
 33  discharge_X_min                      52402 non-null  float64
 34  discharge_X_max                      52402 non-null  float64
 35  discharge_X_range                    52402 non-null  float64
 36  discharge_X_deviation                52402 non-null  float64
 37  discharge_covalent_radius_mean       52402 non-null  float64
 38  discharge_covalent_radius_deviation  52402 non-null  float64
 39  discharge_column_mean                52402 non-null  float64
 40  discharge_column_max                 52402 non-null  float64
 41  discharge_column_min                 52402 non-null  float64
 42  discharge_total_valence_mean         52402 non-null  float64
 43  discharge_stoich_p2                  52402 non-null  float64
 44  discharge_stoich_p5                  52402 non-null  float64
 45  discharge_stoich_p7                  52402 non-null  float64
 46  discharge_stoich_p10                 52402 non-null  float64
dtypes: float64(40), int64(2), object(5)
memory usage: 18.8+ MB

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
average_voltage,52402.0,2.885355,2.371259,-53.697107,2.017523,3.088094,3.905044,132.483476
max_delta_volume_per,52402.0,38.212497,177.153581,0.000185,2.925215,8.404814,22.348703,7325.666208
charge_space_group,52402.0,64.760467,73.788292,1.000000,7.000000,18.000000,136.000000,230.000000
charge_bandgap_minimum,52402.0,0.687142,0.941643,0.000000,0.000000,0.151600,1.160600,8.375100
charge_specific_volume_mode,52402.0,14.471461,18.550728,5.539658,10.720540,11.899108,13.965712,877.005688
charge_specific_volume_range,52402.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
charge_specific_volume_deviation,52402.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
charge_X_mean,52402.0,2.172598,0.376920,0.820000,1.990000,2.110000,2.453333,3.300000
charge_X_min,52402.0,1.285943,0.402806,0.790000,0.980000,0.980000,1.630000,3.160000
charge_X_max,52402.0,3.280048,0.633512,0.820000,3.440000,3.440000,3.440000,3.980000
charge_X_range,52402.0,1.994105,0.766065,0.000000,1.610000,2.460000,2.460000,3.190000
charge_X_deviation,52402.0,0.831636,0.304918,0.000000,0.755000,0.902812,1.016268,1.545000
charge_covalent_radius_mean,52402.0,1.122565,0.175025,0.425000,1.000000,1.116667,1.150000,2.350000
charge_covalent_radius_deviation,52402.0,0.332593,0.119410,0.000000,0.329983,0.361421,0.389444,1.000000
charge_column_mean,52402.0,9.667246,2.718930,1.000000,8.000000,9.666667,11.500000,17.000000
charge_column_max,52402.0,15.250601,3.086679,1.000000,16.000000,16.000000,16.000000,17.000000
charge_column_min,52402.0,3.615072,3.707772,1.000000,1.000000,1.000000,6.000000,17.000000
charge_total_valence_mean,52302.0,2.267026,0.731425,0.500000,1.875000,2.250000,2.666667,8.500000
charge_stoich_p2,52402.0,0.508128,0.141716,0.251200,0.425598,0.499189,0.555556,1.000000
charge_stoich_p5,52402.0,0.160110,0.212298,0.005771,0.062500,0.111350,0.135802,1.000000
charge_stoich_p7,52402.0,0.101765,0.220541,0.000467,0.019936,0.046169,0.058985,1.000000
charge_stoich_p10,52402.0,0.070374,0.224650,0.000011,0.003712,0.012355,0.017358,1.000000
discharge_space_group,52402.0,62.039025,73.050743,1.000000,5.000000,15.000000,125.000000,230.000000
discharge_bandgap_minimum,52402.0,1.167566,1.340079,0.000000,0.000000,0.629450,2.103200,8.716100
discharge_specific_volume_mode,52402.0,13.890632,23.343446,6.888848,9.934983,11.101149,12.595763,665.728350
discharge_specific_volume_range,52402.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
discharge_specific_volume_deviation,52402.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
discharge_X_mean,52402.0,1.989695,0.281806,0.900000,1.986667,2.040000,2.110000,2.804000
discharge_X_min,52402.0,0.978292,0.015079,0.790000,0.980000,0.980000,0.980000,0.980000
discharge_X_max,52402.0,3.280514,0.631765,0.980000,3.440000,3.440000,3.440000,3.980000
discharge_X_range,52402.0,2.302222,0.630059,0.020000,2.460000,2.460000,2.460000,3.190000
discharge_X_deviation,52402.0,0.915794,0.251049,0.010000,0.884364,0.914631,1.051380,1.500000
discharge_covalent_radius_mean,52402.0,1.168492,0.129057,0.750000,1.112500,1.133333,1.183333,1.900000
discharge_covalent_radius_deviation,52402.0,0.341963,0.101162,0.000000,0.337963,0.361421,0.389444,0.819553
discharge_column_mean,52402.0,8.290254,1.948020,1.000000,7.600000,8.500000,9.666667,13.166667
discharge_column_max,52402.0,15.250601,3.086679,1.000000,16.000000,16.000000,16.000000,17.000000
discharge_column_min,52402.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
discharge_total_valence_mean,52402.0,1.978503,0.538181,0.500000,1.666667,2.125000,2.333333,5.000000
discharge_stoich_p2,52402.0,0.415845,0.079638,0.220000,0.368889,0.395556,0.439339,0.986756
discharge_stoich_p5,52402.0,0.070678,0.066930,0.003906,0.033203,0.061017,0.078156,0.967108
discharge_stoich_p7,52402.0,0.028409,0.048031,0.000244,0.007935,0.016388,0.028008,0.954256
discharge_stoich_p10,52402.0,0.009274,0.031684,0.000004,0.000978,0.002801,0.006047,0.935298